spring:
  main:
    allow-bean-definition-overriding : true
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/kotlinplayground}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:070211}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
        defer-datasource-initialization: true

jwt:
  header: ${HEADER:Authorization}
  prefix : ${PREFIX:Bearer}
  secret-key: ${JWT_SECRET_KEY:dfhasjkdfhayffhdtyhdfkjfvfddkvnvssdvnknkknlnkdkmnlvknllnkknlvfdhydshghjkdfaskverafter}
  access-exp: ${JWT_ACCESS_EXP:10000}
  refresh-exp: ${JWT_REFRESH_EXP:604800}

logging:
  level:
    com.example : DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY:a}
      secret-key: ${AWS_SECRET_KEY:a}
    s3:
      bucket: kangsunbucket
    region:
      static: ap-northeast-2

    stack:
  servlet:
    s3:
      bucket: ${BUCKET_NAME:kangsunbucket}
